server.port=8888

spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/donhari2000/rr-hospital-config

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*